### ISSUE TITLE
instant-mocha 1.3.0 prevents reading from files on disk because memfs is used by default

### ISSUE THREAD

**Issue by TauPan** [privatenumber/instant-mocha#18]
## Bug description
I'm reading django templates in my tests to easily mock the DOM (without having loads of html in my test files). This stopped working with existing paths.

`tests/common.js`
~~~js
import * as sinon from "sinon";
import {readFileSync} from "fs";
import * as path from "path";

export const sandbox = sinon.createSandbox();

export var jqInit;
export function stubJqueryInit() {
  jqInit = sandbox.stub($.fn, "init");
};

export function stub_dom(html) {
  // thanks to https://stackoverflow.com/a/4292640/565224
  document.close();
  document.open();
  document.write(html);
  document.close();
};

export function stub_django_template(path) {
  return stub_dom(django_template_contents(path));
}

export const django_templates_basedir = path.normalize(
  `${__dirname}/../../templates`);

export function django_template_contents(path) {
  let fullpath = `${django_templates_basedir}/${path}`,
      contents = readFileSync(fullpath, 'utf-8');
  contents = contents.replace(
    /{%\s*csrf_token\s*%}/m,
    '<input type="hidden" value="csrf_cookie_very_secret" name="csrfmiddlewaretoken">');
  // Maybe just remove other django tags?
  // contents = contents.replace(/{%[^%{}]+}/gm, '');
  return contents;
}

var _old_html = window.document.documentElement.outerHTML;

export function unstub_dom() {
  stub_dom(_old_html);
}
~~~

## Reproduction steps

Upgrade from instant-mocha 1.2.0 to 1.3.0. Afterwards I get the following backtrace from tests that try to use `stub_django_template`:
~~~
  2) module: cpe_jquery
       CPECreateForm
         "before all" hook in "CPECreateForm":
     Error: ENOENT: no such file or directory, open 'airshield/templates/cpes/create_cpe_modal.html'
      at createError (node_modules/memfs/lib/volume.js:121:17)
      at Volume.openFile (node_modules/memfs/lib/volume.js:836:15)
      at Volume.openBase (node_modules/memfs/lib/volume.js:840:25)
      at Volume.openSync (node_modules/memfs/lib/volume.js:851:21)
      at Volume.readFileBase (node_modules/memfs/lib/volume.js:937:23)
      at Volume.readFileSync (node_modules/memfs/lib/volume.js:952:21)
      at django_template_contents (fs-require://1/main.js:3956:66)
      at stub_django_template (fs-require://1/main.js:3964:19)
      at Context.<anonymous> (fs-require://1/main.js:5119:69)
~~~

I've tried adding `path.resolve` but that doesn't help, since the actual filesystem is not used.

I'd appreciate a workaround or a way to disable memfs, preferably for a single test or just the `django_template_contents` function.

## Environment

- instant-mocha version: 1.3.0
- Webpack version: 5.50.0
- Operating System: Linux, openSUSE Leap 15.2, Kernel 5.3.18-lp152.87-preempt
- Node version: v14.17.5
- Package manager (npm/yarn/pnpm) and version: yarn 1.22.10

**Comment by privatenumber** [comment]
Thanks for the report.

This behavior was implemented in fs-require as a security measure, but I've added an option to disable it, which makes sense to do in instant-mocha: https://github.com/privatenumber/fs-require/pull/1

Will update soon.

**Comment by TauPan** [comment]
> Thanks for the report.
> 
> This behavior was implemented in fs-require as a security measure, but [I've added an option to disable it](https://github.com/privatenumber/fs-require/pull/1), which makes sense to do in instant-mocha.
> 
> Will release a fix soon.

I just verified that the fix worked for me. Thanks a lot! I could upgrade instant-mocha and mocha in my codebase now.

Before that I spent some time looking at the fix to see how I could configure this and noticed that you check for `{__dirname: true}` which makes sense and is of course exactly what I need.

Maybe `{__filename: true}` might be relevant here as well?

And I'm wondering if it could make sense to make this more explicit in the configuration.

**Comment by privatenumber** [comment]
`node.__dirname` is a [Webpack configuration to mock it](https://webpack.js.org/configuration/node/#node__dirname). It's not apart of the instant-mocha API/configuration.

**Comment by TauPan** [comment]
Ok, I admit I just don't understand how this works.

You're not obliged to explain of course but thanks for the hint!

**Comment by privatenumber** [comment]
Happy to answer any questions if you have any.

Basically, since Webpack bundles files, `__dirname` and `__filename` no longer work at runtime. For example, a file called `source-file.js` that contains `__dirname` will be bundled into an aggregated file called `bundle.js` in a different directory, so running `bundle.js` will have a different `__dirname` if left untouched.

The Webpack configuration `node.__dirname` tells Webpack to replace `__dirname` with the source file `__dirname` so that when executing `bundle.js`, it knows the original directory name from the source file.
