### ISSUE TITLE
Support webpack config as an esm module like webpack cli does

### ISSUE THREAD

**Issue by kalvenschraut** [privatenumber/instant-mocha#23]
### Feature request

I was digging through the webpack cli to figure out how they did it and I found their function [here](https://github.com/webpack/webpack-cli/blob/9b9040e97c1d7a68d0757c05a67fb0fc8184b827/packages/webpack-cli/lib/webpack-cli.js#L49).  I was able to get this working by changing your code in my repo to do the following

![image](https://user-images.githubusercontent.com/30308012/134251268-4c36c163-c211-4b84-abeb-0015b65a8a17.png)

Those changes seem to be enough to work in my use case, wasn't sure if there is anything else you wanted to look into otherwise I could submit another pull request for this. Seemed pretty small so figured I would just submit my findings and you could change/do what you want with it.

### Why?

I  wanted to convert my project to be module based to be consistent with my use of import/export in my frontend code that is built via webpack.

**Comment by privatenumber** [comment]
Sure, that will be a nice feature!

PR welcome :)

**Comment by privatenumber** [comment]
Closed via https://github.com/privatenumber/instant-mocha/pull/28
