### ISSUE TITLE
Error "Cannot find module 'E:\main.js'" (on windows)

### ISSUE THREAD

**Issue by McBen** [privatenumber/instant-mocha#25]
### Bug description

The unit test runs fine on my regular linux system. When I tried to execute it on my window system I got an error message:

```
Cannot find module 'E:\main.js'
Require stack:
- E:\git\tc\node_modules\fs-require\dist\fs-require.js
- E:\git\tc\node_modules\instant-mocha\dist\lib\memfs.js
- E:\git\tc\node_modules\instant-mocha\dist\lib\mocha.js
- E:\git\tc\node_modules\instant-mocha\dist\instant-mocha.js
- E:\git\tc\node_modules\instant-mocha\dist\cli.js
- E:\git\tc\node_modules\instant-mocha\bin\instant-mocha.js
```

### Reproduction

Removing this line solved my problem:
https://github.com/privatenumber/instant-mocha/blob/36c82bfbd17ae321c235fd399430ea64fa5f74d0/src/lib/mocha.ts#L32

It transforms the `/main.js` into `E:\main.js`.  When using the unmodified name memfs is able to load the file.

### Node.js package manager

yarn

### Environment

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 24.77 GB / 31.91 GB
  Binaries:
    Node: 16.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - C:\Program Files\nodejs\yarn.CMD
    npm: 7.21.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    instant-mocha: ^1.2.0 => 1.3.1
    mocha: ^9.0.3 => 9.1.1
    webpack: ^5.36.2 => 5.51.2
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
Thanks for the bug report.

Perhaps the fix will be to use `path.posix.resolve` for posix specific results.

Will have to create a Windows reproduction to be sure.

**Comment by privatenumber** [comment]
Fixed via https://github.com/privatenumber/instant-mocha/pull/30
