### ISSUE TITLE
Enhance Error Reporting

### ISSUE THREAD

**Issue by MartinLoeper** [privatenumber/instant-mocha#26]
### Feature request

Hi, I just stumbled over this project because I needed webpack v5 support for my project.

I just have a small feature request: Would it be possible to log the full error instead of the error message only?

### Why?

Otherwise it is really hard to trace down webpack compilation errors.

### Additional context

https://github.com/privatenumber/instant-mocha/blob/36c82bfbd17ae321c235fd399430ea64fa5f74d0/src/cli.ts#L48

Maybe replacing with `console.error(error)`?

**Comment by privatenumber** [comment]
Sure, PR welcome!

**Comment by MartinLoeper** [comment]
@privatenumber Just finished one of my Stanford CS251 projects using this tool. Amazing work! Thanks!

**Comment by privatenumber** [comment]
Thanks, glad it helped! 😊

Closed via https://github.com/privatenumber/instant-mocha/pull/27
