### ISSUE TITLE
Add Include parameter

### ISSUE THREAD

**Issue by omaraltayyan** [privatenumber/instant-mocha#3]
As you probably know, `mocha-webpack` has a very useful parameter `--include` that passes a script to execute and include as part of the test bundle, so it would be basically loaded as browser code not nodejs code (which is what `--require` does)

From their [docs](https://zinserjan.github.io/mocha-webpack/docs/installation/cli-usage.html#-require---include)

```
--require, --include

--require is a known mocha option that lets you execute files before your tests will be required. It's useful for setup stuff like initializing jsdom.

--include does something similar, except that the files will be included into the webpack bundle. But like --require they will be executed before your tests.

```

Is there any way to do something similar in `instant-mocha`, and is there any chance such a feature will be added?

**Comment by omaraltayyan** [comment]
It seems using `mocha-cli`'s `--file` argument does something similar to `mocha-webpack`'s `--include`

**Comment by privatenumber** [comment]
Thanks for the issue @omaraltayyan 

Did the `--file` argument work for you?

Seems [based on the doc](https://mochajs.org/#-file-filedirectoryglob) there's a nuance that requires these files to be _test files_, and it sounds like in your case, they might not necessarily be test files

**Comment by omaraltayyan** [comment]
> Thanks for the issue @omaraltayyan
> 
> Did the `--file` argument work for you?
> 
> Seems [based on the doc](https://mochajs.org/#-file-filedirectoryglob) there's a nuance that requires these files to be _test files_, and it sounds like in your case, they might not necessarily be test files

Yes exactly, it had the same effect as the --include argument, maybe mocha cli added it after mochapack did so they kept it, it seems to do the same thing
