### ISSUE TITLE
Support Mocha 9

### ISSUE THREAD

**Issue by amitzur** [privatenumber/instant-mocha#34]
### Feature request

Is there anything preventing `instant-mocha` from specifying version 9 of Mocha as a peer dependency?
A related question is why the range is `^6.1.4 || ^8.3.2`. What is there about version 7 that isn't supported? I would just put `>=6.1.4` for Mocha if that's possible.

### Why?

When running on Node.js 16 on a project that also has Mocha version 9, installing `instant-mocha` gets you this:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: main@1.0.0
npm ERR! Found: mocha@9.1.3
npm ERR! node_modules/mocha
npm ERR!   dev mocha@"^9.1.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer mocha@"^6.1.4 || ^8.3.2" from instant-mocha@1.4.1
npm ERR! node_modules/instant-mocha
npm ERR!   instant-mocha@"^1.4.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by privatenumber** [comment]
I haven't started using Mocha v9 yet, but if you can confirm this works fine with Mocha v9, PR welcome!

And I'm afraid I can't recall why I specified `^6.1.4 || ^8.3.2`.

**Comment by aesy** [comment]
I've tested Mocha 9.1.3 and it seems to work perfectly fine, so [I made a PR](https://github.com/privatenumber/instant-mocha/pull/35) simply just adding `^9.0.0` as a peer dependency.

**Comment by unlight** [comment]
@privatenumber 
It works with mocha 10, please add also support for v10.

**Comment by unlight** [comment]
Workaround with npm 8
  ```
    "overrides": {
      "instant-mocha": {
        "mocha": ">8"
      }
    },
  ``

**Comment by wu-lee** [comment]
My tests also seem to work when I upgrade to mocha@10, but then npm install errors out:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: instant-mocha@1.4.1
npm ERR! Found: mocha@10.1.0
npm ERR! node_modules/mocha
npm ERR!   mocha@"^10.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer mocha@"^6.1.4 || ^8.3.2" from instant-mocha@1.4.1
npm ERR! node_modules/instant-mocha
npm ERR!   dev instant-mocha@"^1.4.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: mocha@8.4.0
npm ERR! node_modules/mocha
npm ERR!   peer mocha@"^6.1.4 || ^8.3.2" from instant-mocha@1.4.1
npm ERR!   node_modules/instant-mocha
npm ERR!     dev instant-mocha@"^1.4.1" from the root project
npm ERR! 
```

**Comment by privatenumber** [comment]
Feel free to pick up the work from https://github.com/privatenumber/instant-mocha/pull/35
